#!/usr/bin/env bash
#
# Generates the two secrets and writes a working mediamtx.yml from the template.
#
# Run once, on the server, before the first `docker compose up -d`. It refuses to overwrite an
# existing config, so re-running it cannot silently invalidate a link you have already shared.

set -euo pipefail
cd "$(dirname "$0")"

TEMPLATE="mediamtx.template.yml"
CONFIG="mediamtx.yml"
ENVFILE="party.env"

if [ -f "$CONFIG" ]; then
    echo "$CONFIG already exists — leaving it alone."
    echo "To roll the secrets, delete it and this script's $ENVFILE, then run again."
    exit 0
fi

command -v openssl >/dev/null || { echo "openssl is required"; exit 1; }

# The path name is the read secret: anyone who knows the URL can watch, so it has to be
# unguessable rather than memorable.
PUBLISH_PASS="$(openssl rand -hex 20)"
PATH_NAME="party-$(openssl rand -hex 12)"
SRT_PASSPHRASE="$(openssl rand -hex 16)"

sed -e "s|__PUBLISH_PASS__|${PUBLISH_PASS}|" \
    -e "s|__PATH_NAME__|${PATH_NAME}|" \
    -e "s|__SRT_PASSPHRASE__|${SRT_PASSPHRASE}|" \
    "$TEMPLATE" > "$CONFIG"

chmod 600 "$CONFIG"

# Written for the host's own reference — it is what the push command needs, and it should never
# leave the machine you push from.
cat > "$ENVFILE" <<EOF
# Generated by setup.sh. Secrets — do not share this file.
PARTY_PATH=${PATH_NAME}
PARTY_PUBLISH_PASS=${PUBLISH_PASS}
PARTY_SRT_PASSPHRASE=${SRT_PASSPHRASE}
EOF
chmod 600 "$ENVFILE"

echo "Wrote $CONFIG and $ENVFILE (both chmod 600)."
echo
echo "  watch URL   https://<your-subdomain>/${PATH_NAME}/index.m3u8"
echo "  push target srt://<your-host>:8890"
echo
echo "The push credentials are in $ENVFILE. Start the server with: docker compose up -d"
