namespace Aetherstream.Plugin.Video;

/// <summary>
/// The show's chef: a Namazu in a toque, drawn as the aquarium draws its fish, in a handful of
/// frames per action. Each frame is a small character map scaled up on the way in.
/// </summary>
internal static class ChefSprite
{
    public enum Action
    {
        Wave,
        Chop,
        Stir,
        Present,
    }

    // k outline, b body, y belly, w toque and apron, e eye, m mouth, r knife, s spoon, p pot,
    // f flame, c board, g greens on the board, t tail fin.
    private static readonly Dictionary<char, uint> Palette = new()
    {
        ['k'] = Canvas.Rgb(0x1A, 0x14, 0x10),
        ['b'] = Canvas.Rgb(0x6E, 0x8C, 0x9E),
        ['y'] = Canvas.Rgb(0xE8, 0xD8, 0xB0),
        ['w'] = Canvas.Rgb(0xF6, 0xF2, 0xEA),
        ['e'] = Canvas.Rgb(0x10, 0x10, 0x10),
        ['m'] = Canvas.Rgb(0xC0, 0x50, 0x50),
        ['r'] = Canvas.Rgb(0xC8, 0xCC, 0xD0),
        ['s'] = Canvas.Rgb(0x8A, 0x5A, 0x2A),
        ['p'] = Canvas.Rgb(0x50, 0x50, 0x58),
        ['f'] = Canvas.Rgb(0xFF, 0x9A, 0x2E),
        ['c'] = Canvas.Rgb(0xB0, 0x82, 0x4A),
        ['g'] = Canvas.Rgb(0x6A, 0xB0, 0x5A),
        ['t'] = Canvas.Rgb(0x56, 0x72, 0x84),
    };

    // The Namazu body, shared: a round head with whiskers, a toque, an apron, a tail off the side.
    // Arms and props differ per frame. 26 wide, 24 tall.
    private static readonly string[][] Wave =
    [
        [
            "..........wwwwww..........",
            ".........wwwwwwww.........",
            ".........wwwwwwww.........",
            "..........wwwwww..........",
            ".........kbbbbbbk.........",
            "........kbbbbbbbbk........",
            ".......kbbebbbbebbk.......",
            "kk.....kbbbbbbbbbbk.....kk",
            "..kkkkkbbbbmmmmbbbbkkkkk..",
            ".......kbbbbbbbbbbk.......",
            "........kbbbbbbbbk........",
            "......kbbbbwwwwbbbbk..bbk.",
            ".....kbbbbwwwwwwbbbbkbbb..",
            ".....kbbbbwwwwwwbbbbkbb...",
            ".....kbbbbwwwwwwbbbbk.....",
            "......kbbbwwwwwwbbbk......",
            ".......kbbwwwwwwbbk.......",
            "........kbbbbbbbbk........",
            ".........kbbbbbbk.........",
            "..........kkkkkk..........",
            "..........................",
            "..........................",
            "..........................",
            "..........................",
        ],
        [
            "..........wwwwww..........",
            ".........wwwwwwww.........",
            ".........wwwwwwww.........",
            "..........wwwwww..........",
            ".........kbbbbbbk.........",
            "........kbbbbbbbbk........",
            ".......kbbebbbbebbk.......",
            "kk.....kbbbbbbbbbbk.....kk",
            "..kkkkkbbbbmmmmbbbbkkkkk..",
            ".......kbbbbbbbbbbk.......",
            "........kbbbbbbbbk...kbbk.",
            "......kbbbbwwwwbbbbk.kbbk.",
            ".....kbbbbwwwwwwbbbbkbbb..",
            ".....kbbbbwwwwwwbbbbkb....",
            ".....kbbbbwwwwwwbbbbk.....",
            "......kbbbwwwwwwbbbk......",
            ".......kbbwwwwwwbbk.......",
            "........kbbbbbbbbk........",
            ".........kbbbbbbk.........",
            "..........kkkkkk..........",
            "..........................",
            "..........................",
            "..........................",
            "..........................",
        ],
    ];

    private static readonly string[][] Chop =
    [
        [
            "..........wwwwww..........",
            ".........wwwwwwww.........",
            ".........wwwwwwww.........",
            "..........wwwwww..........",
            ".........kbbbbbbk.........",
            "........kbbbbbbbbk........",
            ".......kbbebbbbebbk.......",
            "kk.....kbbbbbbbbbbk.....kk",
            "..kkkkkbbbbmmmmbbbbkkkkk..",
            ".......kbbbbbbbbbbk..kr...",
            "........kbbbbbbbbk...kr...",
            "......kbbbbwwwwbbbbk.kr...",
            ".....kbbbbwwwwwwbbbbkbr...",
            ".....kbbbbwwwwwwbbbbkbk...",
            ".....kbbbbwwwwwwbbbbk.....",
            "......kbbbwwwwwwbbbk......",
            ".......kbbwwwwwwbbk.......",
            "........kbbbbbbbbk........",
            "..kccccccccccccccccccccck.",
            "..kcccccgggcccccccggccccck",
            "..kkkkkkkkkkkkkkkkkkkkkkk.",
            "..........................",
            "..........................",
            "..........................",
        ],
        [
            "..........wwwwww..........",
            ".........wwwwwwww.........",
            ".........wwwwwwww.........",
            "..........wwwwww..........",
            ".........kbbbbbbk.........",
            "........kbbbbbbbbk........",
            ".......kbbebbbbebbk.......",
            "kk.....kbbbbbbbbbbk.....kk",
            "..kkkkkbbbbmmmmbbbbkkkkk..",
            ".......kbbbbbbbbbbk.......",
            "........kbbbbbbbbk........",
            "......kbbbbwwwwbbbbk......",
            ".....kbbbbwwwwwwbbbbk.....",
            ".....kbbbbwwwwwwbbbbkbbk..",
            ".....kbbbbwwwwwwbbbbkbbk..",
            "......kbbbwwwwwwbbbk.krrr.",
            ".......kbbwwwwwwbbk..krrrk",
            "........kbbbbbbbbk....kkk.",
            "..kccccccccccccccccccccck.",
            "..kcccccgggccccccgggccccck",
            "..kkkkkkkkkkkkkkkkkkkkkkk.",
            "..........................",
            "..........................",
            "..........................",
        ],
    ];

    private static readonly string[][] Stir =
    [
        [
            "..........wwwwww..........",
            ".........wwwwwwww.........",
            ".........wwwwwwww.........",
            "..........wwwwww..........",
            ".........kbbbbbbk.........",
            "........kbbbbbbbbk........",
            ".......kbbebbbbebbk.......",
            "kk.....kbbbbbbbbbbk.....kk",
            "..kkkkkbbbbmmmmbbbbkkkkk..",
            ".......kbbbbbbbbbbk.....s.",
            "........kbbbbbbbbk.....s..",
            "......kbbbbwwwwbbbbk..s...",
            ".....kbbbbwwwwwwbbbbkbs...",
            ".....kbbbbwwwwwwbbbbkbk...",
            ".....kbbbbwwwwwwbbbbk.....",
            "......kbbbwwwwwwbbbk.kppk.",
            ".......kbbwwwwwwbbk.kppppk",
            "........kbbbbbbbbk..kppppk",
            ".........kbbbbbbk...kppppk",
            "..........kkkkkk.....kkkk.",
            "......................f...",
            ".....................fff..",
            "......................f...",
            "..........................",
        ],
        [
            "..........wwwwww..........",
            ".........wwwwwwww.........",
            ".........wwwwwwww.........",
            "..........wwwwww..........",
            ".........kbbbbbbk.........",
            "........kbbbbbbbbk........",
            ".......kbbebbbbebbk.......",
            "kk.....kbbbbbbbbbbk.....kk",
            "..kkkkkbbbbmmmmbbbbkkkkk..",
            ".......kbbbbbbbbbbk.......",
            "........kbbbbbbbbk........",
            "......kbbbbwwwwbbbbk......",
            ".....kbbbbwwwwwwbbbbk..s..",
            ".....kbbbbwwwwwwbbbbkbbs..",
            ".....kbbbbwwwwwwbbbbkbks..",
            "......kbbbwwwwwwbbbk.kppk.",
            ".......kbbwwwwwwbbk.kppppk",
            "........kbbbbbbbbk..kppppk",
            ".........kbbbbbbk...kppppk",
            "..........kkkkkk.....kkkk.",
            ".......................f..",
            "......................fff.",
            ".......................f..",
            "..........................",
        ],
        [
            "..........wwwwww..........",
            ".........wwwwwwww.........",
            ".........wwwwwwww.........",
            "..........wwwwww..........",
            ".........kbbbbbbk.........",
            "........kbbbbbbbbk........",
            ".......kbbebbbbebbk.......",
            "kk.....kbbbbbbbbbbk.....kk",
            "..kkkkkbbbbmmmmbbbbkkkkk..",
            ".......kbbbbbbbbbbk.......",
            "........kbbbbbbbbk........",
            "......kbbbbwwwwbbbbk......",
            ".....kbbbbwwwwwwbbbbk.....",
            ".....kbbbbwwwwwwbbbbkbbk..",
            ".....kbbbbwwwwwwbbbbkbksss",
            "......kbbbwwwwwwbbbk.kppk.",
            ".......kbbwwwwwwbbk.kppppk",
            "........kbbbbbbbbk..kppppk",
            ".........kbbbbbbk...kppppk",
            "..........kkkkkk.....kkkk.",
            "......................f...",
            ".....................fff..",
            "......................f...",
            "..........................",
        ],
    ];

    private static readonly string[][] Present =
    [
        [
            "..........wwwwww..........",
            ".........wwwwwwww.........",
            ".........wwwwwwww.........",
            "..........wwwwww..........",
            ".........kbbbbbbk.........",
            "........kbbbbbbbbk........",
            ".......kbbebbbbebbk.......",
            "kk.....kbbbbbbbbbbk.....kk",
            "..kkkkkbbbbmmmmbbbbkkkkk..",
            ".......kbbbbbbbbbbk.......",
            "........kbbbbbbbbk........",
            "kbbk..kbbbbwwwwbbbbk..kbbk",
            ".kbbkkbbbbwwwwwwbbbbkkbbk.",
            "..kbbbbbbbwwwwwwbbbbbbbk..",
            ".....kbbbbwwwwwwbbbbk.....",
            "......kbbbwwwwwwbbbk......",
            ".......kbbwwwwwwbbk.......",
            "........kbbbbbbbbk........",
            ".........kbbbbbbk.........",
            "..........kkkkkk..........",
            "..........................",
            "..........................",
            "..........................",
            "..........................",
        ],
        [
            "..........wwwwww..........",
            ".........wwwwwwww.........",
            ".........wwwwwwww.........",
            "..........wwwwww..........",
            ".........kbbbbbbk.........",
            "........kbbbbbbbbk........",
            ".......kbbebbbbebbk.......",
            "kk.....kbbbbbbbbbbk.....kk",
            "..kkkkkbbbbmmmmbbbbkkkkk..",
            ".......kbbbbbbbbbbk.......",
            "kbbk....kbbbbbbbbk....kbbk",
            ".kbbk.kbbbbwwwwbbbbk.kbbk.",
            "..kbbkbbbbwwwwwwbbbbkbbk..",
            "...kbbbbbbwwwwwwbbbbbbk...",
            ".....kbbbbwwwwwwbbbbk.....",
            "......kbbbwwwwwwbbbk......",
            ".......kbbwwwwwwbbk.......",
            "........kbbbbbbbbk........",
            ".........kbbbbbbk.........",
            "..........kkkkkk..........",
            "..........................",
            "..........................",
            "..........................",
            "..........................",
        ],
    ];

    public const int Width = 26;
    public const int Height = 24;

    /// <summary>Draws the chef doing <paramref name="action"/>, the frame chosen by the clock.</summary>
    public static void Draw(Span<uint> target, Action action, double seconds, int x, int y, int scale)
    {
        var (frames, rate) = action switch
        {
            Action.Wave => (Wave, 1.6),
            Action.Chop => (Chop, 3.0),
            Action.Stir => (Stir, 2.2),
            _ => (Present, 1.2),
        };

        var frame = frames[(int)(seconds * rate) % frames.Length];
        Canvas.Sprite(target, frame, c => Palette.GetValueOrDefault(c, 0u), x, y, scale);
    }
}
