namespace Aetherstream.Plugin.Video;

/// <summary>
/// The other shows' hosts, drawn the way the chef is: a ranger in khaki with a bush hat for the
/// wildlife show, and a bard in a chair with a book for the story hour. A few frames each.
/// </summary>
internal static class HostSprites
{
    public enum Ranger
    {
        Stand,
        Creep,
        Grab,
        Run,
        Point,
    }

    public enum Bard
    {
        Read,
        Turn,
        Gesture,
        Wave,
    }

    // k outline, s skin, h hat, t khaki top, l khaki shorts, b boots, e eye, m mouth, r hair,
    // c chair, o book, p page, w white, g gold trim, v velvet.
    private static readonly Dictionary<char, uint> Palette = new()
    {
        ['k'] = Canvas.Rgb(0x1A, 0x14, 0x10),
        ['s'] = Canvas.Rgb(0xE8, 0xB8, 0x90),
        ['h'] = Canvas.Rgb(0xB8, 0x9A, 0x5A),
        ['t'] = Canvas.Rgb(0xC8, 0xB0, 0x78),
        ['l'] = Canvas.Rgb(0xA8, 0x90, 0x5C),
        ['b'] = Canvas.Rgb(0x5A, 0x3C, 0x22),
        ['e'] = Canvas.Rgb(0x10, 0x10, 0x10),
        ['m'] = Canvas.Rgb(0xC0, 0x50, 0x50),
        ['r'] = Canvas.Rgb(0xD8, 0xB0, 0x60),
        ['c'] = Canvas.Rgb(0x6A, 0x2A, 0x2A),
        ['o'] = Canvas.Rgb(0x3A, 0x5A, 0x8A),
        ['p'] = Canvas.Rgb(0xF6, 0xF0, 0xE0),
        ['w'] = Canvas.Rgb(0xF6, 0xF2, 0xEA),
        ['g'] = Canvas.Rgb(0xE0, 0xB8, 0x4A),
        ['v'] = Canvas.Rgb(0x4A, 0x2A, 0x6A),
        ['d'] = Canvas.Rgb(0x30, 0x20, 0x18),
        ['S'] = Canvas.Rgb(0xC8, 0x98, 0x70),
        ['H'] = Canvas.Rgb(0x96, 0x7A, 0x44),
        ['x'] = Canvas.Rgb(0x5A, 0x3C, 0x22),
        ['T'] = Canvas.Rgb(0xA8, 0x92, 0x60),
        ['n'] = Canvas.Rgb(0x9A, 0x84, 0x54),
        ['a'] = Canvas.Rgb(0x4A, 0x30, 0x1A),
        ['L'] = Canvas.Rgb(0x8A, 0x76, 0x48),
        ['u'] = Canvas.Rgb(0xEC, 0xE6, 0xD4),
        ['B'] = Canvas.Rgb(0x2A, 0x1E, 0x14),
    };

    // The ranger: 32 wide, 40 tall. A bush hat with a band and a shaded brim, hair under it, a
    // khaki shirt with a collar and pockets, a belt, shorts, socks, boots.
    private static readonly string[][] RangerStand =
    [
        [
            "..........hhhhhhhhhhh...........",
            ".........hhhhhhhhhhhhh..........",
            ".........hhhhhhhhhhhhh..........",
            ".........hxxxxxxxxxxxh..........",
            "......hhhhhhhhhhhhhhhhhhh.......",
            "....hhHHHHHHHHHHHHHHHHHHHhh.....",
            "......ddddddddddddddddd.........",
            ".........krrrrrrrrrk............",
            ".........ksssssssssk............",
            ".........kseesssseesk...........",
            ".........kssssSssssk............",
            ".........ksssmmmmssk............",
            "..........kssssssSk.............",
            "...........kkssskk..............",
            "........kttttnnttttk............",
            "......kttttttnntttttk...........",
            ".....kttttttttttttttttk.........",
            "....kttnttttttttttnttk..........",
            "....kttntttttaattnttk...........",
            "....ksstttttttttttssk...........",
            "....kSStttttttttttSSk...........",
            ".....kkttttttttttkk.............",
            ".......kaaaaaaaak...............",
            ".......kllllllllk...............",
            ".......kllllllllk...............",
            ".......kLllllllLk...............",
            ".......kllkkkkllk...............",
            ".......kssk..kssk...............",
            ".......kssk..kssk...............",
            ".......kSsk..kSsk...............",
            ".......kuuk..kuuk...............",
            ".......kbbk..kbbk...............",
            ".......kbbbk.kbbbk..............",
            ".......kBBBk.kBBBk..............",
            ".......kkkkk.kkkkk..............",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ],
        [
            "..........hhhhhhhhhhh...........",
            ".........hhhhhhhhhhhhh..........",
            ".........hhhhhhhhhhhhh..........",
            ".........hxxxxxxxxxxxh..........",
            "......hhhhhhhhhhhhhhhhhhh.......",
            "....hhHHHHHHHHHHHHHHHHHHHhh.....",
            "......ddddddddddddddddd.........",
            ".........krrrrrrrrrk............",
            ".........ksssssssssk............",
            ".........kseesssseesk...........",
            ".........kssssSssssk............",
            ".........ksssmmmmssk............",
            "..........kssssssSk.............",
            "...........kkssskk..............",
            "........kttttnnttttk............",
            "......kttttttnntttttk...........",
            ".....kttttttttttttttttk.........",
            "....kttnttttttttttnttk..........",
            "....kttntttttaattnttk...........",
            "....ksstttttttttttssk...........",
            "....kSStttttttttttSSkss.........",
            ".....kkttttttttttkk.............",
            ".......kaaaaaaaak...............",
            ".......kllllllllk...............",
            ".......kllllllllk...............",
            ".......kLllllllLk...............",
            ".......kllkkkkllk...............",
            ".......kssk..kssk...............",
            ".......kssk..kssk...............",
            ".......kSsk..kSsk...............",
            ".......kuuk..kuuk...............",
            ".......kbbk..kbbk...............",
            ".......kbbbk.kbbbk..............",
            ".......kBBBk.kBBBk..............",
            ".......kkkkk.kkkkk..............",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ],
    ];

    private static readonly string[][] RangerCreep =
    [
        [
            "................................",
            "................................",
            "................................",
            "................................",
            "..............hhhhhhhhhhh.......",
            ".............hhhhhhhhhhhhh......",
            ".............hhhhhhhhhhhhh......",
            ".............hxxxxxxxxxxxh......",
            "..........hhhhhhhhhhhhhhhhhhh...",
            "........hhHHHHHHHHHHHHHHHHHHHhh.",
            "..........ddddddddddddddddd.....",
            ".............krrrrrrrrrk........",
            ".............ksssssssssk........",
            ".............kseesssseesk.......",
            ".............kssssSssssk........",
            ".............ksssmmmmssk........",
            "..............kssssssSk.........",
            "...........kttttkkssskk.........",
            ".........kttttttttttk...........",
            ".......kttttttttttttttk.........",
            ".....ksttttnttttttttttk.........",
            "....kssttttntttttttttttk........",
            "....kSsttttttttaaattttttk.......",
            "....kkkttttttttttttttttsk.......",
            ".......kkkttttttttttttSSk.......",
            "..........kaaaaaaaaaakkk........",
            "..........kllllllllllk..........",
            "..........kllllllllllk..........",
            "...........kLllllllLk...........",
            "..........kssk...kssk...........",
            ".........kssk....kssk...........",
            "........kSsk.....kSsk...........",
            "........kuuk.....kuuk...........",
            "........kbbk.....kbbk...........",
            "........kbbbk....kbbbk..........",
            "........kBBBk....kBBBk..........",
            "........kkkkk....kkkkk..........",
            "................................",
            "................................",
            "................................",
        ],
        [
            "................................",
            "................................",
            "................................",
            "................................",
            "..............hhhhhhhhhhh.......",
            ".............hhhhhhhhhhhhh......",
            ".............hhhhhhhhhhhhh......",
            ".............hxxxxxxxxxxxh......",
            "..........hhhhhhhhhhhhhhhhhhh...",
            "........hhHHHHHHHHHHHHHHHHHHHhh.",
            "..........ddddddddddddddddd.....",
            ".............krrrrrrrrrk........",
            ".............ksssssssssk........",
            ".............kseesssseesk.......",
            ".............kssssSssssk........",
            ".............ksssmmmmssk........",
            "..............kssssssSk.........",
            "...........kttttkkssskk.........",
            ".........kttttttttttk...........",
            ".......kttttttttttttttk.........",
            ".....ksttttnttttttttttk.........",
            "....kssttttntttttttttttk........",
            "....kSsttttttttaaattttttk.......",
            "....kkkttttttttttttttttsk.......",
            ".......kkkttttttttttttSSk.......",
            "..........kaaaaaaaaaakkk........",
            "..........kllllllllllk..........",
            "..........kllllllllllk..........",
            "...........kLllllllLk...........",
            "..........kssk...kssk...........",
            "..........kssk....kssk..........",
            "..........kSsk.....kSsk.........",
            "..........kuuk.....kuuk.........",
            "..........kbbk.....kbbk.........",
            "..........kbbbk....kbbbk........",
            "..........kBBBk....kBBBk........",
            "..........kkkkk....kkkkk........",
            "................................",
            "................................",
            "................................",
        ],
    ];

    private static readonly string[][] RangerGrab =
    [
        [
            "..........hhhhhhhhhhh...........",
            ".........hhhhhhhhhhhhh..........",
            ".........hhhhhhhhhhhhh..........",
            ".........hxxxxxxxxxxxh..........",
            "......hhhhhhhhhhhhhhhhhhh.......",
            "....hhHHHHHHHHHHHHHHHHHHHhh.....",
            "......ddddddddddddddddd.........",
            ".........krrrrrrrrrk............",
            ".........ksssssssssk............",
            ".........kseesssseesk...........",
            ".........kssssSssssk............",
            ".........kssmwwwmssk............",
            "..........kssssssSk.............",
            "...........kkssskk..............",
            "........kttttnnttttk............",
            "......kttttttnntttttkss.........",
            ".....kttttttttttttttttksss......",
            "....kttntttttttttttttttssss.....",
            "....kttntttttaattttttttSSSS.....",
            "....kssttttttttttttttkkkk.......",
            "....kSSttttttttttttkk...........",
            ".....kkttttttttttkk.............",
            ".......kaaaaaaaak...............",
            ".......kllllllllk...............",
            ".......kllllllllk...............",
            ".......kLllllllLk...............",
            ".......kllkkkkllk...............",
            ".......kssk..kssk...............",
            ".......kssk..kssk...............",
            ".......kSsk..kSsk...............",
            ".......kuuk..kuuk...............",
            ".......kbbk..kbbk...............",
            ".......kbbbk.kbbbk..............",
            ".......kBBBk.kBBBk..............",
            ".......kkkkk.kkkkk..............",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ],
        [
            "..........hhhhhhhhhhh...........",
            ".........hhhhhhhhhhhhh..........",
            ".........hhhhhhhhhhhhh..........",
            ".........hxxxxxxxxxxxh..........",
            "......hhhhhhhhhhhhhhhhhhh.......",
            "....hhHHHHHHHHHHHHHHHHHHHhh.....",
            "......ddddddddddddddddd.........",
            ".........krrrrrrrrrk............",
            ".........ksssssssssk............",
            ".........kseesssseesk...........",
            ".........kssssSssssk............",
            ".........kssmwwwmssk............",
            "..........kssssssSk.............",
            "...........kkssskk..............",
            "........kttttnnttttk............",
            "......kttttttnntttttk...........",
            ".....kttttttttttttttttkss.......",
            "....kttntttttttttttttttsss......",
            "....kttntttttaattttttttssss.....",
            "....kssttttttttttttttkkkk.......",
            "....kSSttttttttttttkk...........",
            ".....kkttttttttttkk.............",
            ".......kaaaaaaaak...............",
            ".......kllllllllk...............",
            ".......kllllllllk...............",
            ".......kLllllllLk...............",
            ".......kllkkkkllk...............",
            ".......kssk..kssk...............",
            ".......kssk..kssk...............",
            ".......kSsk..kSsk...............",
            ".......kuuk..kuuk...............",
            ".......kbbk..kbbk...............",
            ".......kbbbk.kbbbk..............",
            ".......kBBBk.kBBBk..............",
            ".......kkkkk.kkkkk..............",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ],
    ];

    private static readonly string[][] RangerRun =
    [
        [
            "......hhhhhhhhhhh...............",
            ".....hhhhhhhhhhhhh..............",
            ".....hhhhhhhhhhhhh..............",
            ".....hxxxxxxxxxxxh..............",
            "..hhhhhhhhhhhhhhhhhhh...........",
            "hhHHHHHHHHHHHHHHHHHHHhh.........",
            "..ddddddddddddddddd.............",
            ".....krrrrrrrrrk................",
            ".....ksssssssssk................",
            ".....kseesssseesk...............",
            ".....kssssSssssk................",
            ".....kssmwwwwmsk................",
            "......kssssssSk.................",
            ".......kkssskk..................",
            "....kttttnnttttk................",
            "..kttttttnntttttkss.............",
            "kttttttttttttttttksss...........",
            "ssnttttttttttntttk..............",
            "SSnttttttaattntttk..............",
            "..kkttttttttttttttk.............",
            ".....kttttttttttttk.............",
            "......kkttttttttttk.............",
            "........kaaaaaaaaak.............",
            "........kllllllllllk............",
            ".......kllllllllllllk...........",
            "......kLllllkkkkllllLk..........",
            ".....kssk........kssk...........",
            "....kssk..........kssk..........",
            "...kSsk............kSsk.........",
            "..kuuk..............kuuk........",
            ".kbbk................kbbk.......",
            "kbbbk................kbbbk......",
            "kBBBk................kBBBk......",
            "kkkkk................kkkkk......",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ],
        [
            "......hhhhhhhhhhh...............",
            ".....hhhhhhhhhhhhh..............",
            ".....hhhhhhhhhhhhh..............",
            ".....hxxxxxxxxxxxh..............",
            "..hhhhhhhhhhhhhhhhhhh...........",
            "hhHHHHHHHHHHHHHHHHHHHhh.........",
            "..ddddddddddddddddd.............",
            ".....krrrrrrrrrk................",
            ".....ksssssssssk................",
            ".....kseesssseesk...............",
            ".....kssssSssssk................",
            ".....kssmwwwwmsk................",
            "......kssssssSk.................",
            ".......kkssskk..................",
            "....kttttnnttttkss..............",
            "..kttttttnntttttksss............",
            "kttttttttttttttttk..............",
            "kknttttttttttntttk..............",
            "ssnttttttaattntttk..............",
            "SSkttttttttttttttk..............",
            ".....kttttttttttttk.............",
            "......kkttttttttttk.............",
            "........kaaaaaaaaak.............",
            "........kllllllllllk............",
            ".........kllllllllk.............",
            ".........kLllllllLk.............",
            "........kssk..kssk..............",
            "........kssk...kssk.............",
            "........kSsk....kSsk............",
            "........kuuk.....kuuk...........",
            "........kbbk......kbbk..........",
            "........kbbbk.....kbbbk.........",
            "........kBBBk.....kBBBk.........",
            "........kkkkk.....kkkkk.........",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ],
    ];

    private static readonly string[][] RangerPoint =
    [
        [
            "..........hhhhhhhhhhh...........",
            ".........hhhhhhhhhhhhh..........",
            ".........hhhhhhhhhhhhh..........",
            ".........hxxxxxxxxxxxh..........",
            "......hhhhhhhhhhhhhhhhhhh.......",
            "....hhHHHHHHHHHHHHHHHHHHHhh.....",
            "......ddddddddddddddddd.........",
            ".........krrrrrrrrrk............",
            ".........ksssssssssk............",
            ".........kseesssseesk...........",
            ".........kssssSssssk............",
            ".........ksssmmmmssk............",
            "..........kssssssSk.............",
            "...........kkssskk..............",
            "........kttttnnttttk............",
            "......kttttttnntttttk...........",
            ".....kttttttttttttttttkssssss...",
            "....kttnttttttttttntttttSSSSSs..",
            "....kttntttttaattnttk...........",
            "....ksstttttttttttk.............",
            "....kSSttttttttttk..............",
            ".....kkttttttttttkk.............",
            ".......kaaaaaaaak...............",
            ".......kllllllllk...............",
            ".......kllllllllk...............",
            ".......kLllllllLk...............",
            ".......kllkkkkllk...............",
            ".......kssk..kssk...............",
            ".......kssk..kssk...............",
            ".......kSsk..kSsk...............",
            ".......kuuk..kuuk...............",
            ".......kbbk..kbbk...............",
            ".......kbbbk.kbbbk..............",
            ".......kBBBk.kBBBk..............",
            ".......kkkkk.kkkkk..............",
            "................................",
            "................................",
            "................................",
            "................................",
            "................................",
        ],
    ];

    // The bard: 30 wide, 30 tall, seated in a high-backed chair with a book open on the lap.
    private static readonly string[][] BardRead =
    [
        [
            "..cccccccccccccc..............",
            ".cccccccccccccccc.............",
            ".ccvvvvvvvvvvvvcc.............",
            ".ccvvvvvvvvvvvvcc.............",
            ".ccvvvvrrrrrvvvcc.............",
            ".ccvvvrrrrrrrvvcc.............",
            ".ccvvvksssssskvcc.............",
            ".ccvvvkseesesskcc.............",
            ".ccvvvkssssssskcc.............",
            ".ccvvvkssmmmsskcc.............",
            ".ccvvvvksssskvvcc.............",
            ".ccvvvvvkssklvvcc.............",
            ".ccvvvggggggggvcc.............",
            ".ccvvggggggggggcc.............",
            ".ccvgggggggggggcc.............",
            ".ccvggsgggggggsccc............",
            ".ccvggsggggggsccc.............",
            ".ccvvkssoooooossk.............",
            ".ccvvkssoppppposk.............",
            ".ccvvkssopppppokk.............",
            ".ccvvkkkooooookk..............",
            ".ccvvvvvvvvvvvcc..............",
            ".ccvvvvvvvvvvvcc..............",
            ".cccccccccccccccc.............",
            ".ccddddddddddddcc.............",
            ".cc............cc.............",
            ".cc............cc.............",
            "..............................",
            "..............................",
            "..............................",
        ],
        [
            "..cccccccccccccc..............",
            ".cccccccccccccccc.............",
            ".ccvvvvvvvvvvvvcc.............",
            ".ccvvvvvvvvvvvvcc.............",
            ".ccvvvvrrrrrvvvcc.............",
            ".ccvvvrrrrrrrvvcc.............",
            ".ccvvvksssssskvcc.............",
            ".ccvvvksseseeskcc.............",
            ".ccvvvkssssssskcc.............",
            ".ccvvvkssmmmsskcc.............",
            ".ccvvvvksssskvvcc.............",
            ".ccvvvvvkssklvvcc.............",
            ".ccvvvggggggggvcc.............",
            ".ccvvggggggggggcc.............",
            ".ccvgggggggggggcc.............",
            ".ccvggsgggggggsccc............",
            ".ccvggsggggggsccc.............",
            ".ccvvkssoooooossk.............",
            ".ccvvkssoppppposk.............",
            ".ccvvkssopppppokk.............",
            ".ccvvkkkooooookk..............",
            ".ccvvvvvvvvvvvcc..............",
            ".ccvvvvvvvvvvvcc..............",
            ".cccccccccccccccc.............",
            ".ccddddddddddddcc.............",
            ".cc............cc.............",
            ".cc............cc.............",
            "..............................",
            "..............................",
            "..............................",
        ],
    ];

    private static readonly string[][] BardTurn =
    [
        [
            "..cccccccccccccc..............",
            ".cccccccccccccccc.............",
            ".ccvvvvvvvvvvvvcc.............",
            ".ccvvvvvvvvvvvvcc.............",
            ".ccvvvvrrrrrvvvcc.............",
            ".ccvvvrrrrrrrvvcc.............",
            ".ccvvvksssssskvcc.............",
            ".ccvvvkseesesskcc.............",
            ".ccvvvkssssssskcc.............",
            ".ccvvvkssmmmsskcc.............",
            ".ccvvvvksssskvvcc.............",
            ".ccvvvvvkssklvvcc.............",
            ".ccvvvggggggggvcc.............",
            ".ccvvggggggggggcc.............",
            ".ccvgggggggggggcc..ss.........",
            ".ccvggsgggggggggggss..........",
            ".ccvggsgggggggggg.............",
            ".ccvvkssoooooossk.............",
            ".ccvvkssoppppposk.............",
            ".ccvvkssoppppppp..............",
            ".ccvvkkkooooookk..............",
            ".ccvvvvvvvvvvvcc..............",
            ".ccvvvvvvvvvvvcc..............",
            ".cccccccccccccccc.............",
            ".ccddddddddddddcc.............",
            ".cc............cc.............",
            ".cc............cc.............",
            "..............................",
            "..............................",
            "..............................",
        ],
    ];

    private static readonly string[][] BardGesture =
    [
        [
            "..cccccccccccccc..............",
            ".cccccccccccccccc.............",
            ".ccvvvvvvvvvvvvcc.............",
            ".ccvvvvvvvvvvvvcc.............",
            ".ccvvvvrrrrrvvvcc.............",
            ".ccvvvrrrrrrrvvcc.............",
            ".ccvvvksssssskvcc.............",
            ".ccvvvkseesesskcc.............",
            ".ccvvvkssssssskcc.............",
            ".ccvvvkssmmmsskcc.............",
            ".ccvvvvksssskvvcc.....ss......",
            ".ccvvvvvkssklvvcc....ss.......",
            ".ccvvvggggggggvcc...gg........",
            ".ccvvggggggggggcc..gg.........",
            ".ccvgggggggggggggggg..........",
            ".ccvggsgggggggggggg...........",
            ".ccvggsgggggggggg.............",
            ".ccvvkssoooooossk.............",
            ".ccvvkssoppppposk.............",
            ".ccvvkssopppppokk.............",
            ".ccvvkkkooooookk..............",
            ".ccvvvvvvvvvvvcc..............",
            ".ccvvvvvvvvvvvcc..............",
            ".cccccccccccccccc.............",
            ".ccddddddddddddcc.............",
            ".cc............cc.............",
            ".cc............cc.............",
            "..............................",
            "..............................",
            "..............................",
        ],
        [
            "..cccccccccccccc..............",
            ".cccccccccccccccc.............",
            ".ccvvvvvvvvvvvvcc.............",
            ".ccvvvvvvvvvvvvcc.............",
            ".ccvvvvrrrrrvvvcc.............",
            ".ccvvvrrrrrrrvvcc.............",
            ".ccvvvksssssskvcc.............",
            ".ccvvvkseesesskcc.............",
            ".ccvvvkssssssskcc.............",
            ".ccvvvkssmmmsskcc.............",
            ".ccvvvvksssskvvcc.............",
            ".ccvvvvvkssklvvcc.............",
            ".ccvvvggggggggvcc.....ss......",
            ".ccvvggggggggggcc...ggss......",
            ".ccvggggggggggggggggg.........",
            ".ccvggsgggggggggggg...........",
            ".ccvggsgggggggggg.............",
            ".ccvvkssoooooossk.............",
            ".ccvvkssoppppposk.............",
            ".ccvvkssopppppokk.............",
            ".ccvvkkkooooookk..............",
            ".ccvvvvvvvvvvvcc..............",
            ".ccvvvvvvvvvvvcc..............",
            ".cccccccccccccccc.............",
            ".ccddddddddddddcc.............",
            ".cc............cc.............",
            ".cc............cc.............",
            "..............................",
            "..............................",
            "..............................",
        ],
    ];

    public static void DrawRanger(Span<uint> target, Ranger action, double seconds, int x, int y, int scale, bool flip = false)
    {
        var (frames, rate) = action switch
        {
            Ranger.Stand => (RangerStand, 1.4),
            Ranger.Creep => (RangerCreep, 2.0),
            Ranger.Grab => (RangerGrab, 4.0),
            Ranger.Run => (RangerRun, 6.0),
            _ => (RangerPoint, 1.0),
        };

        var frame = frames[(int)(seconds * rate) % frames.Length];
        Canvas.Sprite(target, frame, c => Palette.GetValueOrDefault(c, 0u), x, y, scale, flip);
    }

    public static void DrawBard(Span<uint> target, Bard action, double seconds, int x, int y, int scale)
    {
        var (frames, rate) = action switch
        {
            Bard.Read => (BardRead, 0.7),
            Bard.Turn => (BardTurn, 1.0),
            _ => (BardGesture, 1.6),
        };

        var frame = frames[(int)(seconds * rate) % frames.Length];
        Canvas.Sprite(target, frame, c => Palette.GetValueOrDefault(c, 0u), x, y, scale);
    }
}
